name: UniLMMV
channels:
  - pytorch
  - defaults
dependencies:
  - pip=23.3.1
  - numpy=1.26.3
  - python=3.9.18
  - pip:
    - einops==0.7.0
    - matplotlib==3.8.2
    - monai==1.3.0
    - pandas==2.2.0
    - scikit-image==0.22.0
    - scikit-learn==1.4.0
    - seaborn==0.13.1
    - tensorboardx==2.6.2.2
    - torch==2.1.2
    - torchaudio==2.1.2
    - torchvision==0.16.2